#!/bin/bash
set -eu

cd "$(dirname $0)"

bold=$(tput bold)
green=$(tput setaf 2)
normal=$(tput sgr0)

title() {
  echo "${bold}====> $1${normal}"
  echo
}

indent() {
  sed 's/^/  /'
  echo
}

echo

# Create directories
mkdir -p ~/Code/Repos
mkdir -p ~/Code/Forks
mkdir -p ~/Code/Job
mkdir -p ~/Code/Sandbox

# Install symlinks
title "Configuring software..."
./install-symlinks

# Set MacOS defaults
title "Setting MacOS defaults..."
./osx_defaults

echo "${green}🏠 Welcome home!${normal}" | indent